import { useEffect, useState } from "react";
import {
  emailMonthlyReport,
  UncertainExternalFinancialMutationError,
  type FinancialData,
} from "@/lib/financial-api";
import { type MonthlyReportFacts } from "@/lib/monthly-report";
import { budgetTotalForMonth, calculateTargetRetirementMonth, formatDateOnly, type MonthlyReportMetricFormat, type MonthlyReportSnapshot } from "@/lib/storage";
import { generateFinancialCalendar } from "@/lib/financial-calendar";
import { goalStatus } from "@/lib/goals";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@workspace/wealthone-design-system/components/ui/card";
import { Button } from "@workspace/wealthone-design-system/components/ui/button";
import { Printer, Mail, FileBarChart, RefreshCw, TriangleAlert } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@workspace/wealthone-design-system/components/ui/accordion";
import { useToast } from "@workspace/wealthone-design-system/hooks/use-toast";

function monthKey(date: Date) {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`;
}

function reportMetric(
  report: MonthlyReportSnapshot | undefined,
  sectionId: MonthlyReportSnapshot["sections"][number]["id"],
  key: string,
) {
  return report?.sections.find((section) => section.id === sectionId)?.metrics[key] ?? 0;
}

export function factsForMonth(data: FinancialData, reportDate: Date): MonthlyReportFacts {
  const month = monthKey(reportDate);
  const monthEnd = new Date(reportDate.getFullYear(), reportDate.getMonth() + 1, 0);
  const previousDate = new Date(reportDate.getFullYear(), reportDate.getMonth() - 1, 1);
  const previousMonth = monthKey(previousDate);
  const previousReport = data.monthlyReports.find((report) => report.month === previousMonth);
  const retirementMonth = calculateTargetRetirementMonth({
    dateOfBirth: data.profileInputs.dateOfBirth,
    targetRetirementAge: data.retirementInputs.targetRetirementAge,
  });
  const events = generateFinancialCalendar({
    from: formatDateOnly(reportDate),
    through: formatDateOnly(monthEnd),
    incomes: data.incomeSources,
    ...(retirementMonth ? { retirementDate: formatDateOnly(retirementMonth) } : {}),
  });
  const expectedIncome = events
    .filter((event) => event.kind === "income")
    .reduce((sum, event) => sum + (event.amount ?? 0), 0);
  const actualIncome = data.incomeReceipts
    .filter((receipt) => receipt.receivedDate.startsWith(month))
    .reduce((sum, receipt) => sum + receipt.amount, 0);
  const expenses = data.expenses.filter((expense) => expense.date.startsWith(month));
  const actualExpenses = expenses.reduce((sum, expense) => sum + expense.amount, 0);
  const categoryTotals = expenses.reduce<Record<string, number>>((totals, expense) => {
    totals[expense.category] = (totals[expense.category] ?? 0) + expense.amount;
    return totals;
  }, {});
  const [topExpenseCategory = "No expense category", topExpenseCategoryAmount = 0] =
    Object.entries(categoryTotals).sort(([, left], [, right]) => right - left)[0] ?? [];
  const savingsAmount = actualIncome - actualExpenses;
  // This helper is for previews only. Immutable reports are generated by the
  // server at the month boundary, when the live portfolio is a historical fact.
  const existingReport = data.monthlyReports.find((report) => report.month === month);
  const isCurrentMonth = month === monthKey(new Date());
  const livePortfolioValue = data.investments.reduce(
    (sum, investment) => sum + investment.currentValue,
    0,
  );
  const totalInvested = data.investments.reduce(
    (sum, investment) => sum + investment.investedAmount,
    0,
  );
  const portfolioValue = isCurrentMonth ? livePortfolioValue : reportMetric(
    existingReport, "portfolio-value-returns-change", "value",
  );
  const previousPortfolio = reportMetric(
    previousReport,
    "portfolio-value-returns-change",
    "value",
  );
  const snapshot = data.netWorthSnapshots.find((item) => item.month === month);
  const previousSnapshot = data.netWorthSnapshots.find((item) => item.month === previousMonth);
  const netWorth = snapshot?.netWorth ?? 0;
  const healthScore = snapshot?.healthScore ?? 0;
  const expenseBudget = budgetTotalForMonth(data.budgets, reportDate);
  const actionCandidates: string[] = [];

  if (expenseBudget > 0 && actualExpenses > expenseBudget) {
    actionCandidates.push("Reduce next month’s flexible spending to return below budget.");
  }
  if (actualIncome > 0 && savingsAmount / actualIncome < 0.2) {
    actionCandidates.push("Move one planned amount toward a 20% monthly savings rate.");
  }
  if (data.goals.some((goal) => ["behind", "overdue"].includes(goalStatus(goal, monthEnd)))) {
    actionCandidates.push("Review allocations for goals that are behind schedule.");
  }
  if (data.emergencyFund.reserveBalance < Math.max(1, actualExpenses) * data.emergencyFund.targetMonths) {
    actionCandidates.push("Check the emergency-fund target and next contribution.");
  }
  actionCandidates.push(
    "Review next month’s calendar for large payments and deadlines.",
    "Confirm recurring income and investment schedules are still accurate.",
    "Review retirement assumptions after any major income or spending change.",
  );

  return {
    month,
    actualIncome,
    expectedIncome,
    actualExpenses,
    expenseBudget,
    expenseCategoryCount: new Set(expenses.map((expense) => expense.category)).size,
    topExpenseCategory,
    topExpenseCategoryAmount,
    savingsAmount,
    savingsRatePercent: actualIncome > 0 ? savingsAmount / actualIncome * 100 : 0,
    portfolioValue,
    portfolioReturnChange: previousPortfolio > 0 ? portfolioValue - previousPortfolio : 0,
    portfolioReturnPercent: totalInvested > 0
      ? (portfolioValue - totalInvested) / totalInvested * 100
      : 0,
    netWorth,
    netWorthChange: previousSnapshot ? netWorth - previousSnapshot.netWorth : 0,
    retirementDateMovementMonths: 0,
    healthScore,
    healthScoreChange: previousSnapshot ? healthScore - (previousSnapshot.healthScore ?? 0) : 0,
    nextMonthActions: actionCandidates.slice(0, 3),
  };
}

function formatMetric(value: number, format: MonthlyReportMetricFormat) {
  switch (format) {
    case "currency":
      return value.toLocaleString("en-IN", { style: "currency", currency: "INR" });
    case "percent":
      return `${value.toLocaleString("en-IN", { maximumFractionDigits: 1 })}%`;
    case "count":
    case "number":
      return value.toLocaleString("en-IN", { maximumFractionDigits: 1 });
  }
}

function reportMetricTone(
  sectionId: MonthlyReportSnapshot["sections"][number]["id"],
  key: string,
  value: number,
  sections?: MonthlyReportSnapshot["sections"],
) {
  if (sectionId === "income-vs-expected") {
    if (key === "actual") return value > 0 ? "text-positive" : value < 0 ? "text-negative" : "text-foreground";
    if (key === "variance") return value > 0 ? "text-positive" : value < 0 ? "text-negative" : "text-foreground";
  }
  if (sectionId === "expenses-vs-budget-category") {
    if (key === "actual" || key === "topCategorySpend") return "text-foreground";
  }
  if (sectionId === "savings-amount-rate") {
    if (key === "amount") return value > 0 ? "text-warning" : value < 0 ? "text-negative" : "text-foreground";
    if (key === "rate") {
      const actualIncome = sections?.find((item) => item.id === "income-vs-expected")?.metrics.actual;
      if (typeof actualIncome !== "number" || actualIncome <= 0) return "text-foreground";
      return value >= 20 ? "text-positive" : "text-negative";
    }
  }
  if (sectionId === "portfolio-value-returns-change") {
    if (key === "value") return value > 0 ? "text-positive" : value < 0 ? "text-negative" : "text-foreground";
    if (key === "returnChange" || key === "returnPercent") {
      return value > 0 ? "text-positive" : value < 0 ? "text-negative" : "text-foreground";
    }
  }
  if (sectionId === "net-worth-change" && key === "change") {
    return value > 0 ? "text-positive" : value < 0 ? "text-negative" : "text-foreground";
  }
  return "text-foreground";
}

function ReportSectionContent({
  section,
  sections,
  forecast,
}: {
  section: MonthlyReportSnapshot["sections"][number];
  sections: MonthlyReportSnapshot["sections"];
  forecast?: MonthlyReportSnapshot["retirementForecast"];
}) {
  return (
    <>
      <div className="mb-4 grid grid-cols-2 gap-4 md:grid-cols-4">
        {section.id === "retirement-date-movement" && forecast && (
          <div className="col-span-2 rounded-lg bg-muted p-3 md:col-span-4 print:border-b print:bg-transparent print:p-0">
            <div className="mb-1 text-xs text-muted-foreground">Projected retirement date</div>
            <div className="text-lg font-semibold">
              {forecast.projectedRetirementMonth
                ? new Date(`${forecast.projectedRetirementMonth}-01T12:00:00`).toLocaleDateString(undefined, { month: "long", year: "numeric" })
                : "Not yet funded before life expectancy"}
            </div>
            <div className="text-xs text-muted-foreground">Modeled as of {new Date(`${forecast.asOfDate}T12:00:00`).toLocaleDateString()}</div>
          </div>
        )}
        {Object.entries(section.metrics).map(([key, value]) => (
          <div key={key} className="rounded-lg bg-muted p-3 print:border-b print:bg-transparent print:p-0">
            <div className="mb-1 text-xs capitalize text-muted-foreground">
              {key.replace(/([A-Z])/g, " $1")}
            </div>
            <div className={`text-lg font-semibold ${reportMetricTone(section.id, key, value, sections)}`}>
              {formatMetric(value, section.metricFormats[key] ?? "number")}
            </div>
          </div>
        ))}
        {(section.unavailableMetrics ?? []).map((key) => (
          <div key={key} className="rounded-lg bg-muted p-3 print:border-b print:bg-transparent print:p-0">
            <div className="mb-1 text-xs capitalize text-muted-foreground">
              {key.replace(/([A-Z])/g, " $1")}
            </div>
            <div className="text-sm font-semibold text-muted-foreground">Not available</div>
          </div>
        ))}
      </div>
      {section.actions.length > 0 && (
        <div className="mt-4 rounded-lg bg-secondary/20 p-4 print:border print:bg-transparent">
          <div className="mb-2 text-sm font-medium">Action items</div>
          <ol className="ml-5 list-decimal space-y-1 text-sm text-muted-foreground">
            {section.actions.map((action) => <li key={action}>{action}</li>)}
          </ol>
        </div>
      )}
    </>
  );
}

export function ReportsView({ data }: { data: FinancialData }) {
  const { toast } = useToast();
  const [emailingId, setEmailingId] = useState<string>();
  const [printingId, setPrintingId] = useState<string>();
  const [deliveryFailures, setDeliveryFailures] = useState(data.monthlyReportEmailFailures);

  const printReport = (id: string) => {
    setPrintingId(id);
    document.body.dataset.monthlyReportPrint = "true";
    window.setTimeout(() => window.print(), 0);
  };

  const finishPrinting = () => {
    delete document.body.dataset.monthlyReportPrint;
    setPrintingId(undefined);
  };

  useEffect(() => {
    window.addEventListener("afterprint", finishPrinting);
    return () => {
      window.removeEventListener("afterprint", finishPrinting);
      delete document.body.dataset.monthlyReportPrint;
    };
  }, []);

  useEffect(() => {
    setDeliveryFailures(data.monthlyReportEmailFailures);
  }, [data.monthlyReportEmailFailures]);

  const sendEmail = async (report: MonthlyReportSnapshot) => {
    setEmailingId(report.id);
    try {
      const updated = await emailMonthlyReport(report.id);
      setDeliveryFailures(updated.monthlyReportEmailFailures);
      toast({
        title: "Monthly report emailed",
        description: updated.monthlyReportEmailStatusPendingMonths.includes(report.month)
          ? "It was sent to your account email. Delivery status will update later."
          : "It was sent to your account email.",
      });
    } catch (error) {
      if (
        error instanceof UncertainExternalFinancialMutationError
        && error.reconciledData
      ) {
        setDeliveryFailures(error.reconciledData.monthlyReportEmailFailures);
      }
      toast({
        title: "Monthly report could not be emailed",
        description: error instanceof Error ? error.message : "Try again later.",
        variant: "default",
      });
    } finally {
      setEmailingId(undefined);
    }
  };

  if (data.monthlyReports.length === 0) {
    return (
      <Card className="flex flex-col items-center justify-center p-12 text-center text-muted-foreground">
        <FileBarChart className="mb-4 h-12 w-12 text-muted-foreground" />
        <p>No monthly reports yet.</p>
        <p className="mt-2 text-sm">Reports are saved once per month and remain available here.</p>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      {data.monthlyReports.map((report) => (
        <Card
          key={report.id}
          className="monthly-report-card print:mb-8 print:border-0 print:shadow-none"
          data-print-selected={printingId === report.id ? "true" : undefined}
        >
          <CardHeader className="print:px-0">
            {deliveryFailures[report.month] && (
              <div className="mb-4 flex gap-3 rounded-lg border border-destructive/40 bg-destructive/5 p-4 text-sm print:hidden" role="alert">
                <TriangleAlert className="mt-0.5 h-5 w-5 shrink-0 text-destructive" />
                <div>
                  <p className="font-medium">Email delivery needs attention</p>
                  <p className="text-muted-foreground">
                    {deliveryFailures[report.month].category === "report_too_large"
                      ? "This report is too large to email. You can still print or save it as a PDF here."
                      : deliveryFailures[report.month].category === "email_unavailable"
                        ? "Report email is not available right now. Your report remains saved here."
                        : "The email service could not deliver this report. Try emailing it again."}
                    {" "}Last attempt {new Date(deliveryFailures[report.month].failedAt).toLocaleString()}.
                  </p>
                </div>
              </div>
            )}
            <div className="flex items-start justify-between gap-4">
              <div>
                <CardTitle>
                  Report for {new Date(`${report.month}-01T12:00:00`).toLocaleDateString(undefined, {
                    month: "long",
                    year: "numeric",
                  })}
                </CardTitle>
                <CardDescription>
                  Generated {new Date(report.generatedAt).toLocaleDateString()}
                </CardDescription>
              </div>
              <div className="flex flex-wrap justify-end gap-2 print:hidden">
                <Button variant="outline" size="sm" onClick={() => printReport(report.id)}>
                  <Printer className="mr-2 h-4 w-4" />
                  Print / save PDF
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  disabled={emailingId === report.id}
                  onClick={() => void sendEmail(report)}
                >
                  {emailingId === report.id
                    ? <RefreshCw className="mr-2 h-4 w-4 animate-spin" />
                    : <Mail className="mr-2 h-4 w-4" />}
                  Email this report
                </Button>
              </div>
            </div>
          </CardHeader>
          <CardContent className="print:px-0">
            <Accordion type="single" collapsible className="w-full print:hidden">
              {report.sections.map((section) => (
                <AccordionItem key={section.id} value={section.id}>
                  <AccordionTrigger className="hover:no-underline">{section.title}</AccordionTrigger>
                  <AccordionContent><ReportSectionContent section={section} sections={report.sections} forecast={report.retirementForecast} /></AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
            <div className="hidden space-y-6 print:block">
              {report.sections.map((section) => (
                <section key={section.id}>
                  <h2 className="mb-3 mt-5 text-lg font-bold">{section.title}</h2>
                  <ReportSectionContent section={section} sections={report.sections} forecast={report.retirementForecast} />
                </section>
              ))}
            </div>
          </CardContent>
        </Card>
      ))}
    </div>
  );
}
