export default async function handler(req: any, res: any) {
	// The bundle is generated by the Vercel build command and has no source declaration.
	// @ts-ignore Generated Vercel bundle has no checked-in declaration.
	const { default: app } = await import("../artifacts/api-server/dist/vercel.mjs");
	return app(req, res);
}